version: "3"
services:

  # Liferay
  liferay:
   image: chris-testliferay
   # deploy:
   #   limits:
   #       memory: 1000M
    ports:
      - "38085:8080"
   #   - "11311:11311"
    volumes:
      - ./liferay/mount:/etc/liferay/mount
    environment:
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL=jdbc:postgresql://postgres:5432/lportal
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME=postgres
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD=postgres
      - LIFERAY_EDITOR_PERIOD_WYSIWYG_PERIOD_DEFAULT=ckeditor

  # Elasticsearch
  elasticsearch:
    image: christ-testelastic
    #deploy:
    #  limits:
    #      memory: 1000M
    #ports:
    #  - "9200:9200"
    # - "9300:9300"
    volumes:
      - ./elasticsearch/data/:/usr/share/elasticsearch/data/
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/config/logging.yml:/usr/share/elasticsearch/config/logging.yml
      - ./elasticsearch/config/userdict_ja.txt:/usr/share/elasticsearch/config/userdict_ja.txt
      - ./elasticsearch/logs/:/var/log/elasticsearch/
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.graph.enabled=false
      - xpack.ml.enabled=false
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.4
    ports:
      - "35601:5601"
    environment:
      - xpack.security.enabled=false
  
  # Postgres
  postgres:
    image: chris-testpostgres
    environment:
      POSTGRES_PASSWORD: postgres
    #  context: ./postgres
   # ports:
   #   - "35432:5432"
  #  volumes:
   #   - christ-test:/var/lib/postgresql/data
